import { Project } from '../../types';
import { CodeXml } from 'lucide-react';
import { Database } from 'lucide-react';
import { Workflow } from 'lucide-react';

export const projects: Project[] = [
  {
    id: 'job-listings-aggregator',
    title: 'Job Listings Aggregator',
    subtitle: 'Python, Selenium, BeautifulSoup, FastAPI, SQLAlchemy, PostgreSQL, Pandas, Docker',
    year: 2026,
    icon: Database,
    highlights: [
      'Built an automated job-scraping pipeline aggregating listings from multiple sources into a searchable REST API and dashboard.',
      'Implemented a resilient scraping architecture using Selenium for JS-rendered sites and requests/BeautifulSoup for static sites, with per-source error isolation so a single failed page/site never breaks the pipeline.',
      'Built a FastAPI REST API with 6+ combinable filters (skill, location, remote status, experience, source, free-text search) and pagination.',
      'Implemented hash-based deduplication with a DB-level unique constraint, preventing duplicate postings across repeated scrapes.',
      'Automated hourly refresh via APScheduler/cron and email digests for newly discovered postings.',
      'Containerized with Docker (Chromium + chromedriver bundled) for one-command deployment and wrote automated tests covering the API, filters, and deduplication logic.',
    ],
    technologies: [
      'Python',
      'Selenium',
      'BeautifulSoup',
      'FastAPI',
      'SQLAlchemy',
      'PostgreSQL',
      'Pandas',
      'Docker',
    ],
  },
  {
    id: 'coinpulse',
    title: 'CoinPulse',
    subtitle: 'Crypto Market ETL Platform',
    year: 2026,
    icon: Database,
    highlights: [
      'Production-grade end-to-end ETL pipeline ingesting CoinGecko market data into PostgreSQL warehouse.',
      'Automated daily extraction & transformation across 100+ cryptocurrency assets.',
      'Idempotent upserts with primary-key conflict handling for data integrity.',
      'Orchestrated with Apache Airflow DAGs in a Dockerized environment.',
    ],
    technologies: [
      'Python',
      'PostgreSQL',
      'Airflow',
      'Docker',
      'REST API',
    ],
  },
  {
    id: 'logpulse',
    title: 'LogPulse',
    subtitle: 'Application Log Analytics Pipeline',
    year: 2026,
    icon: Workflow,
    highlights: [
      'Scalable batch pipeline transforming unstructured logs into structured relational records.',
      'Field extraction, parsing, and validation for analytics-ready datasets.',
      'SQL-based KPI dashboards for request volume, status distribution, and error trends.',
      'Normalized schemas and indexing strategies for efficient querying.',
    ],
    technologies: [
      'Python',
      'PostgreSQL',
      'Batch Processing',
      'SQL Analytics',
    ],
  },
  {
    id: 'fraud-detection',
    title: 'Credit Card Fraud Detection',
    subtitle: 'ML Data Pipeline',
    year: 2025,
    icon: CodeXml,
    highlights: [
      'End-to-end preprocessing and feature engineering on 1M+ transactional records.',
      'Data cleaning, normalization, SMOTE resampling to address class imbalance.',
      'Automated transformation workflows producing standardized model-ready datasets.',
    ],
    technologies: [
      'Python',
      'Pandas',
      'NumPy',
      'Feature Engineering',
    ],
  },
  {
    id: 'movie-analytics-dashboard',
    title: 'Interactive Movie Analytics Dashboard',
    subtitle: 'Python, Pandas, NumPy, Plotly, Dash',
    year: 2025,
    icon: CodeXml,
    highlights: [
      'Built an interactive dashboard to analyze movie revenue, ratings, trends, and performance metrics.',
      'Created dynamic visualizations including KPIs, bar charts, trend analysis, and distribution plots.',
      'Performed full data preprocessing including cleaning, deduplication, and metric creation.',
      'Implemented user-driven filters and deployed the dashboard using a production-ready structure.',
    ],
    technologies: [
      'Python',
      'Pandas',
      'NumPy',
      'Plotly',
      'Dash',
    ],
  },
  {
    id: 'breast-cancer-detection',
    title: 'Breast Cancer Detection — MSc Dissertation',
    subtitle: 'Python, CNN, TensorFlow, PyTorch, Medical Imaging, Statistical Analysis',
    year: 2026,
    icon: CodeXml,
    highlights: [
      'Developed a deep learning classification model for breast cancer detection using histopathological image data as part of MSc dissertation research.',
      'Applied Convolutional Neural Networks (CNNs) with transfer learning to classify malignant vs. benign tissue samples, achieving strong diagnostic performance metrics.',
      'Conducted statistical analysis of model outputs including ROC-AUC, precision/recall, and confusion matrix evaluation to ensure clinical-grade reliability.',
      'Addressed class imbalance through data augmentation and resampling strategies, improving minority-class recall.',
      'Produced detailed research documentation covering methodology, experimental design, results analysis, and conclusions — demonstrating end-to-end project ownership.',
    ],
    technologies: [
      'Python',
      'TensorFlow',
      'PyTorch',
      'CNNs',
      'Medical Imaging',
    ],
  },
];