import { Experience } from '../../types';

export const experiences: Experience[] = [
    {
        id: 'telus',
        role: 'Consultant / Contractor',
        company: 'TELUS Digital',
        location: 'Remote, Noida, India',
        dates: 'Aug 2021 — Dec 2025',
        bullets: [
            'Worked as a Contractor on the Sapphire team, contributing to CASA, a customer support application used by call center agents to access customer profiles, billing information, service plans, offers, and account dashboards in real time.',
            'Developed and enhanced features in a React.js and Node.js application, integrating secure backend services to retrieve and display offers data from downstream APIs; used Redux and Redux-Thunk to consume and manage backend API responses.',
            'Collaborated with API teams to implement a layered API architecture, where frontend services consumed intermediary APIs that securely accessed and aggregated data from backend systems.',
            'On the backend, consumed downstream APIs and performed data sanitization (Node.js/JavaScript) to return only relevant data to the frontend.',
            'Wrote unit tests using React Testing Library and Jenkins for frontend, and Jest for backend; used Redis for caching and GCP Secret Manager for secure credential storage.',
            'Monitored GCP Logs for errors and warnings; debugged and resolved production issues faced by customer care agents in real time during live customer calls.',
            'Participated in the organization’s transition from monolithic architecture to microservices, decomposing application modules into independently deployable services to improve scalability and maintainability.',
            'Later joined the API development team, designing and maintaining downstream APIs using Python, FastAPI, and PostgreSQL, supporting data integration, business workflows, and enterprise applications; optimized API performance, backend processing logic, and database queries, improving response times and system reliability.',
            'Worked within Agile teams using Git-based version control, contributing to production releases and maintaining high service stability across customer-facing systems.',
        ],
        tech: ['Python', 'SQL', 'REST APIs', 'Git', 'Agile'],
        filled: true,
    },
    {
        id: 'etelligens',
        role: 'Frontend Developer',
        company: 'Etelligens Technologies',
        location: 'Remote, Noida, India',
        dates: 'Dec 2020 — Dec 2025',
        bullets: [
            'Maintained and shipped new features for TravelNet, a hybrid mobile application, and Alloodo, a game-rental client website (frontend maintenance and feature enhancement).',
            'Developed production-grade React.js and AngularJS applications, consuming backend REST APIs and optimizing data-driven UI performance across 5+ client projects, including Pyro, Local Kings, and Huskarma.',
            'Collaborated with distributed engineering teams in remote environments, consistently delivering features on schedule across Agile sprint cycles.',
        ],
        tech: ['React.js', 'AngularJS', 'APIs', 'Agile'],
        filled: false,
    },
    // {
    //     id: 'globiz',
    //     role: 'Mobile Application Developer',
    //     company: 'Globiz Technology Inc.',
    //     location: 'Remote, Ludhiana, India',
    //     dates: 'Jun 2020 — Dec 2020',
    //     bullets: [
    //     'Member of both the design and development teams; delivered fully responsive, cross-browser-tested, pixel-perfect static website designs from mockups, and pixel-perfect mobile app screens from UI mockups in React Native.',
    //     'Developed hybrid mobile applications using React Native, consuming RESTful APIs and integrating structured backend data into performant mobile UIs, including LocalCart and LineManagement (deployed to Google Play Store).',
    //     ],
    //     tech: ['React Native', 'REST APIs', 'Mobile'],
    //     filled: false,
    // },
    {
        id: 'promatics',
        role: 'Web Designer',
        company: 'Promatics Technologies Pvt. Ltd.',
        location: 'Ludhiana, India',
        dates: 'Aug 2018 — May 2020',
        bullets: [
            'Promoted from Web Designer to Associate Frontend Developer within one year in recognition of strong technical performance, rapid skill development, and consistent project contributions.',
            'Designed responsive website mockups, mobile application UI mockups, and branding assets (logos, banners, marketing graphics) using Adobe Photoshop and Adobe Illustrator.',
            'Converted approved UI/UX designs into responsive, cross-browser compatible web interfaces using HTML5, CSS3, JavaScript/jQuery, and Bootstrap.',
            'Collaborated with designers, developers, and project managers to deliver multiple client-facing websites from design through frontend implementation.',
            'Contributed to frontend feature development, UI enhancements, bug fixes, and production-ready web pages across multiple projects.',
            'Built and maintained reusable UI components while ensuring responsive design and a consistent user experience across desktop and mobile devices.',
            'Selected Portfolio: UCatch, PortaPrep, Babzer, GPS Colombia (Design).',
        ],
        tech: ['HTML/CSS', 'JavaScript', 'UI Design'],
        filled: false,
    },
];